/**
 * Glyph Definitions
 * 24 consonant glyphs with full metadata, segments, and phonetic properties
 */

import { THEME } from "./theme";

export const CONS = [
  {
    num: 1,
    name: "S",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["TL", "TC"],
      ["TL", "ML"],
    ],
    breath: "up",
    bn: "TL",
    ipa: "/s/",
    desc: "Sharp Hiss",
  },
  {
    num: 2,
    name: "F",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["TL", "TC"],
      ["TC", "TR"],
    ],
    breath: "up",
    bn: "TC",
    ipa: "/f/",
    desc: "Friction Breath",
  },
  {
    num: 3,
    name: "SH",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["TC", "TR"],
      ["TR", "MR"],
    ],
    breath: "up",
    bn: "TR",
    ipa: "/ʃ/",
    desc: "Soft Sibilant",
  },
  {
    num: 4,
    name: "Z",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["TL", "ML"],
      ["ML", "MC"],
    ],
    breath: "up",
    bn: "ML",
    ipa: "/z/",
    desc: "Voiced Hiss",
  },
  {
    num: 5,
    name: "ZH",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["TC", "MC"],
      ["MC", "MR"],
    ],
    breath: "up",
    bn: "MC",
    ipa: "/ʒ/",
    desc: "Voiced Sibilant",
  },
  {
    num: 6,
    name: "TH",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["TR", "MR"],
      ["MR", "BR"],
    ],
    breath: "up",
    bn: "MR",
    ipa: "/θ/",
    desc: "Dental Fricative",
  },
  {
    num: 7,
    name: "DH",
    type: "sibilant",
    color: THEME.accentSibilant,
    segs: [
      ["ML", "MC"],
      ["MC", "BC"],
    ],
    breath: "up",
    bn: "MC",
    ipa: "/ð/",
    desc: "Voiced Dental",
  },
  {
    num: 8,
    name: "K",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["TL", "ML"],
      ["ML", "BL"],
    ],
    breath: "hold",
    bn: "ML",
    ipa: "/k/",
    desc: "Velar Stop",
  },
  {
    num: 9,
    name: "T",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["ML", "MC"],
      ["MC", "MR"],
      ["TC", "MC"],
      ["MC", "BC"],
    ],
    breath: "hold",
    bn: "MC",
    ipa: "/t/",
    desc: "Alveolar Stop",
  },
  {
    num: 10,
    name: "P",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["TR", "MR"],
      ["MR", "BR"],
    ],
    breath: "hold",
    bn: "MR",
    ipa: "/p/",
    desc: "Bilabial Stop",
  },
  {
    num: 11,
    name: "B",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["ML", "MC"],
      ["MC", "BC"],
    ],
    breath: "hold",
    bn: "MC",
    ipa: "/b/",
    desc: "Voiced Bilabial",
  },
  {
    num: 12,
    name: "D",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["TC", "MC"],
      ["MC", "BC"],
    ],
    breath: "hold",
    bn: "MC",
    ipa: "/d/",
    desc: "Voiced Alveolar",
  },
  {
    num: 13,
    name: "G",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["ML", "MC"],
      ["MC", "MR"],
    ],
    breath: "hold",
    bn: "MC",
    ipa: "/g/",
    desc: "Voiced Velar",
  },
  {
    num: 14,
    name: "K'",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["TL", "ML"],
      ["ML", "BL"],
      ["BL", "BC"],
    ],
    breath: "hold",
    bn: "BL",
    ipa: "/kʼ/",
    desc: "Ejective Velar",
  },
  {
    num: 15,
    name: "T'",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["ML", "MC"],
      ["MC", "MR"],
      ["TC", "MC"],
    ],
    breath: "hold",
    bn: "MC",
    ipa: "/tʼ/",
    desc: "Ejective Alveolar",
  },
  {
    num: 16,
    name: "P'",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [
      ["TR", "MR"],
      ["MR", "BR"],
      ["BR", "BC"],
    ],
    breath: "hold",
    bn: "BR",
    ipa: "/pʼ/",
    desc: "Ejective Bilabial",
  },
  {
    num: 17,
    name: "ʔ",
    type: "plosive",
    color: THEME.accentPlosive,
    segs: [["MC", "BC"]],
    breath: "hold",
    bn: "BC",
    ipa: "/ʔ/",
    desc: "Glottal Stop",
  },
  {
    num: 18,
    name: "NG",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["ML", "BL"],
      ["BL", "BC"],
    ],
    breath: "down",
    bn: "BL",
    ipa: "/ŋ/",
    desc: "Velar Nasal",
  },
  {
    num: 19,
    name: "M",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["BL", "BC"],
      ["BC", "BR"],
    ],
    breath: "down",
    bn: "BC",
    ipa: "/m/",
    desc: "Bilabial Nasal",
  },
  {
    num: 20,
    name: "L",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["BC", "BR"],
      ["MR", "BR"],
    ],
    breath: "down",
    bn: "BR",
    ipa: "/l/",
    desc: "Lateral Approximant",
  },
  {
    num: 21,
    name: "N",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["BL", "BC"],
      ["MC", "BC"],
    ],
    breath: "down",
    bn: "BC",
    ipa: "/n/",
    desc: "Alveolar Nasal",
  },
  {
    num: 22,
    name: "R",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["BC", "BR"],
      ["MC", "BC"],
    ],
    breath: "down",
    bn: "BC",
    ipa: "/r/",
    desc: "Alveolar Trill",
  },
  {
    num: 23,
    name: "W",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["MR", "BR"],
      ["MC", "BC"],
    ],
    breath: "down",
    bn: "BC",
    ipa: "/w/",
    desc: "Labiovelar Approximant",
  },
  {
    num: 24,
    name: "Y",
    type: "resonant",
    color: THEME.accentResonant,
    segs: [
      ["ML", "BL"],
      ["MR", "BR"],
    ],
    breath: "down",
    bn: "BL",
    ipa: "/j/",
    desc: "Palatal Approximant",
  },
];

// Precomputed lookup maps
export const BY_NUM = Object.fromEntries(CONS.map((c) => [c.num, c]));
export const BY_NAME = Object.fromEntries(CONS.map((c) => [c.name, c]));

// Freeze to prevent accidental mutations
Object.freeze(CONS);
Object.freeze(BY_NUM);
Object.freeze(BY_NAME);

export default { CONS, BY_NUM, BY_NAME };
